"""Article 17 compliance certificate — PDF generation + email outbound stub.

Generates a signed-looking PDF that a DPO can hand to the data subject
confirming erasure. For demo we stamp it as a "demo certificate" and write
to disk; for production this would be sealed via DocuSign / Notary.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

CERT_DIR = Path(os.environ.get("CERT_DIR", "data/certificates"))


def generate_cert(request_id: str, subject: str, article: str,
                  files_processed: int, findings_erased: int,
                  matches: list[dict] | None = None) -> Path:
    CERT_DIR.mkdir(parents=True, exist_ok=True)
    path = CERT_DIR / f"{request_id}.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4,
                            leftMargin=64, rightMargin=64, topMargin=64, bottomMargin=64)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Title"], fontName="Times-Roman",
                                  fontSize=22, leading=26, spaceAfter=18)
    body_style = ParagraphStyle("body", parent=styles["BodyText"], fontName="Helvetica",
                                 fontSize=10.5, leading=15)
    meta_style = ParagraphStyle("meta", parent=styles["BodyText"], fontName="Helvetica",
                                 fontSize=8.5, textColor=HexColor("#6f6555"), leading=12,
                                 spaceAfter=12)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontName="Times-Roman",
                         fontSize=14, leading=18, spaceBefore=12, spaceAfter=8)

    now = datetime.utcnow().strftime("%d %B %Y · %H:%M UTC")
    flow = [
        Paragraph("Certificate of Erasure", title_style),
        Paragraph(f"Issued under Article {article} of the General Data Protection Regulation (EU) 2016/679",
                  meta_style),
        Spacer(1, 6),
        Paragraph(
            f"This is to certify that the personal data of <b>{subject}</b> has been erased "
            f"from the systems described below, pursuant to the data-subject's request "
            f"received and validated under Article {article}.",
            body_style,
        ),
        Spacer(1, 12),
        Paragraph("Summary", h2),
        Table(
            [
                ["Request ID", request_id],
                ["Subject", subject],
                ["Article invoked", f"Art. {article} GDPR"],
                ["Files processed", str(files_processed)],
                ["Findings erased", str(findings_erased)],
                ["Issued", now],
                ["Controller", "Robert Bosch GmbH — DPO Office"],
                ["Status", "Erased — confirmed by automated audit log"],
            ],
            colWidths=[140, 320],
            style=TableStyle([
                ("FONT", (0, 0), (-1, -1), "Helvetica", 9.5),
                ("TEXTCOLOR", (0, 0), (0, -1), HexColor("#6f6555")),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, HexColor("#d8cdb8")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]),
        ),
    ]

    if matches:
        flow.append(Paragraph("Affected Repositories", h2))
        rows = [["#", "File", "Action"]]
        for i, m in enumerate(matches[:30], start=1):
            rows.append([str(i), m.get("file_path", "?"), m.get("proposed_action", "delete")])
        flow.append(Table(
            rows,
            colWidths=[24, 360, 80],
            style=TableStyle([
                ("FONT", (0, 0), (-1, -1), "Helvetica", 8.5),
                ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8.5),
                ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#6f6555")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.6, HexColor("#2a2620")),
                ("LINEBELOW", (0, 0), (-1, -1), 0.3, HexColor("#d8cdb8")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]),
        ))

    flow.append(Spacer(1, 24))
    flow.append(Paragraph(
        "This certificate is generated by Forgetter, the Bosch GDPR data-discovery system. "
        "Processing performed locally on Bosch infrastructure; no personal data was transmitted "
        "outside the controller's environment during the discovery, decision, or erasure phases.",
        meta_style,
    ))
    flow.append(Paragraph(
        f"Document hash anchor: {request_id} · issued {now}",
        ParagraphStyle("hash", parent=styles["Code"], fontName="Courier",
                       fontSize=8, textColor=HexColor("#9a8e78")),
    ))

    doc.build(flow, onFirstPage=_stamp, onLaterPages=_stamp)
    return path


def _stamp(c: canvas.Canvas, _doc) -> None:
    """Watermark + signature line for credibility."""
    c.saveState()
    c.setStrokeColor(HexColor("#b9c441"))
    c.setLineWidth(0.5)
    c.line(64, 50, 545, 50)
    c.setFont("Helvetica", 7.5)
    c.setFillColor(HexColor("#6f6555"))
    c.drawString(64, 38, "Forgetter — Bosch GDPR Data Discovery · Local-First AI · cert/v1")
    c.drawRightString(545, 38, f"Page {c.getPageNumber()}")
    c.restoreState()


def send_email_stub(to: str, subject_line: str, body: str,
                    attachment_path: Path | None = None) -> Path:
    """Don't actually SMTP — write the .eml to disk so we can show it in the demo
    as "sent items". In production: hook up SES / SMTP / Microsoft Graph send.
    """
    outbox = Path(os.environ.get("OUTBOX_DIR", "data/outbox"))
    outbox.mkdir(parents=True, exist_ok=True)
    msg = EmailMessage()
    msg["From"] = "privacy@bosch.example"
    msg["To"] = to
    msg["Subject"] = subject_line
    msg["Date"] = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")
    msg.set_content(body)
    if attachment_path and attachment_path.exists():
        with attachment_path.open("rb") as f:
            msg.add_attachment(f.read(), maintype="application", subtype="pdf",
                               filename=attachment_path.name)
    eml_path = outbox / f"{datetime.utcnow().strftime('%Y%m%dT%H%M%S')}-{to.replace('@', '_at_')}.eml"
    with eml_path.open("wb") as f:
        f.write(bytes(msg))
    return eml_path
